Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2019-12, with the labels that each got.

#115 AP638 Categorise benefits as included/excluded
  .gitignore
  Gemfile
  Gemfile.lock
  app/models/state_benefit_type.rb
  db/migrate/20191202153330_create_state_benefit_types.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/data/state_benefit_types.yml
Labels: ready for code review

#112 AP-641 Test Payment Period Analyser
  Gemfile
  Gemfile.lock
  app/controllers/assessments_controller.rb
  app/services/payment_period_analyser.rb
  app/services/time_series_calculator.rb
  lib/tasks/payment_dates_generator.rake
  spec/fixtures/generated_payment_dates.csv
  spec/fixtures/payment_periods.csv
  spec/services/integration_tests/test_runner_spec.rb
  spec/services/payment_dates_generator_spec.rb
  spec/services/payment_period_analyser_spec.rb
  spec/support/payment_dates_generator.rb
Labels: Approved

#116 AP-1101 Add other income endpoint
  app/controllers/incomes_controller.rb
  app/controllers/other_incomes_controller.rb
  app/models/assessment.rb
  app/models/gross_income_summary.rb
  app/models/other_income_payment.rb
  app/models/other_income_source.rb
  app/models/wage_slip.rb
  app/services/assessment_creation_service.rb
  app/services/income_creation_service.rb
  app/services/integration_tests/test_runner.rb
  app/services/other_incomes_creation_service.rb
  config/initializers/apipie.rb
  config/routes.rb
  db/migrate/20191202142321_create_gross_income_summaries.rb
  db/migrate/20191205155502_add_other_income_sources.rb
  db/migrate/20191205164153_create_other_income_payments.rb
  db/schema.rb
  doc/apipie_examples.json
  lib/tasks/generate_docs.rake
  spec/factories/assessment_factory.rb
  spec/factories/gross_income_summary_factory.rb
  spec/models/wage_slip_spec.rb
  spec/requests/incomes_spec.rb
  spec/requests/other_incomes_spec.rb
  spec/services/income_creation_service_spec.rb
Labels: ready for code review

#119 AP-1103 Calculate gross income threshold
  app/controllers/assessments_controller.rb
  app/models/assessment.rb
  app/models/gross_income_summary.rb
  app/services/base_workflow_service.rb
  app/services/workflow_service/gross_income_collator.rb
  config/thresholds/8-Apr-2018.yml
  config/thresholds/8-Apr-2019.yml
  config/thresholds/8-Apr-2020.yml
  db/migrate/20191206141200_add_upper_threshold_to_gross_income_summary.rb
  db/schema.rb
  spec/factories/assessment_factory.rb
  spec/factories/dependant_factory.rb
  spec/models/gross_income_summary_spec.rb
  spec/requests/assessments_spec.rb
  spec/services/workflow_service/gross_income_collator_spec.rb
Labels: ready for code review

#120 AP-1127 Calculate monthly value for OtherIncome
  app/models/assessment.rb
  app/models/assessment_error.rb
  app/models/other_income_source.rb
  app/services/monthly_other_income_calculator.rb
  app/services/payment_period_data_extractor.rb
  app/services/unearned_income_monthly_conversion_service.rb
  db/migrate/20191205155502_add_other_income_sources.rb
  db/migrate/20191205164153_create_other_income_payments.rb
  db/migrate/20191209131409_add_monthly_oher_income_to_gross_income_summary.rb
  db/migrate/20191210100303_create_assessment_errors.rb
  db/migrate/20191210102843_drop_wage_slips.rb
  db/migrate/20191211161738_add_fields_to_other_payments.rb
  db/schema.rb
  spec/factories/gross_income_summary_factory.rb
  spec/factories/other_income_payment_factory.rb
  spec/factories/other_income_source_factory.rb
  spec/models/other_income_source_spec.rb
  spec/services/payment_period_data_extractor_spec.rb
  spec/services/unearned_income_monthly_conversion_service_spec.rb
  spec/support/faker/other_income_source.rb
Labels: Changes requested, ready for code review

#123 Add 2020 gross income threshold values
  config/thresholds/8-Apr-2020.yml
Labels: ready for code review

#124 AP1100 State benefits endpoint
  .circleci/config.yml
  app/controllers/state_benefits_controller.rb
  app/models/gross_income_summary.rb
  app/models/state_benefit.rb
  app/models/state_benefit_payment.rb
  app/models/state_benefit_type.rb
  app/services/state_benefits_creation_service.rb
  config/routes.rb
  db/migrate/20191209134932_create_state_benefits.rb
  db/migrate/20191209161655_create_state_benefit_payments.rb
  db/migrate/20191211101351_change_state_benefit_type_name.rb
  db/schema.rb
  db/seeds/data/state_benefit_types.yml
  doc/apipie_examples.json
  spec/factories/state_benefit_type.rb
  spec/models/state_benefit_spec.rb
  spec/requests/state_benefits_spec.rb
Labels: Changes requested, ready for code review

#126 AP-1136 - Implement passported assesment using workflow
  app/controllers/assessments_controller.rb
  app/models/capital_summary.rb
  app/models/gross_income_summary.rb
  app/services/assessors/capital_assessor.rb
  app/services/assessors/main_assessor.rb
  app/services/base_workflow_service.rb
  app/services/workflows/main_workflow.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/passported_workflow.rb
  app/workflows/standard_workflow.rb
  db/migrate/20191205155502_add_other_income_sources.rb
  db/migrate/20191213112436_add_assessment_result_to_gross_income_summaries.rb
  db/schema.rb
  spec/factories/applicant_factory.rb
  spec/fixtures/integration_test_data.xlsx
  spec/integration/test_runner_spec.rb
  spec/models/capital_summary_spec.rb
  spec/requests/assessments_spec.rb
  spec/services/assessors/main_assessor_spec.rb
  spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
  spec/services/workflows/main_workflow_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/services/workflows/passported_workflow_spec.rb
  spec/support/attribute_matcher.rb
Labels: ready for code review

#129 AP-1135 Non-passported workflow
  app/models/assessment.rb
  app/models/benefit_receipt.rb
  app/services/assessors/disposable_income_assessor.rb
  app/services/assessors/gross_income_assessor.rb
  app/services/base_workflow_service.rb
  app/services/collators/outgoings_collator.rb
  app/services/workflows/non_passported_workflow.rb
  app/services/workflows/self_employed_workflow.rb
  db/migrate/20191218113121_drop_benefit_receipts.rb
  db/migrate/20191218115258_add_self_employed_to_applicants.rb
  db/schema.rb
  spec/models/benefit_receipt_spec.rb
  spec/services/utilities/payment_period_analyser_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/services/workflows/self_employed_workflow_spec.rb
Labels: ready for code review

#133 Add State Benefits to the Gross Income Summary
  app/models/state_benefit.rb
  app/services/base_workflow_service.rb
  app/services/collators/state_benefit_collator.rb
  db/migrate/20191219113329_add_state_benefit_to_gross_income_summary.rb
  db/migrate/20191219113400_add_monthly_amount_to_state_benefits.rb
  db/schema.rb
  spec/factories/benefit_receipt_factory.rb
  spec/factories/state_benefit_factory.rb
  spec/factories/state_benefit_payment_factory.rb
  spec/factories/state_benefit_type_factory.rb
  spec/services/collators/state_benefit_collator_spec.rb
Labels: Approved

#130 AP-1134 Gross income assessment
  app/services/assessors/gross_income_assessor.rb
  app/services/base_workflow_service.rb
  app/services/collators/gross_income_collator.rb
  db/migrate/20191220085420_drop_statuses.rb
  db/schema.rb
  spec/services/assessors/gross_income_assessor_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
Labels: Approved

#134 AP-1120 Update State Benefit Type seeds with DWP codes
  db/migrate/20191220091038_add_code_to_state_benefit_types.rb
  db/schema.rb
  db/seeds.rb
  db/seeds/data/state_benefit_types.yml
Labels: ready for code review

#136 AP1157 DisposableIncomeSummary model and migration file
  app/models/assessment.rb
  app/models/disposable_income_summary.rb
  db/migrate/20191223132825_create_disposable_income_summaries.rb
  db/schema.rb
Labels: ready for code review

#137 AP1159 Outgoings tables
  .rubocop_todo.yml
  app/controllers/outgoings_controller.rb
  app/models/assessment.rb
  app/models/disposable_income_summary.rb
  app/models/outgoing.rb
  app/models/outgoings/base_outgoing.rb
  app/models/outgoings/childcare.rb
  app/models/outgoings/housing_cost.rb
  app/models/outgoings/maintenance.rb
  app/services/creators/outgoings_creator.rb
  db/migrate/20191230112317_drop_old_outgoings.rb
  db/migrate/20191230112428_create_new_outgoings.rb
  db/schema.rb
  spec/factories/disposable_income_summary_factory.rb
  spec/factories/outgoing_factory.rb
  spec/requests/outgoings_spec.rb
  spec/services/creators/outgoings_creator_spec.rb
Labels: ready for code review

#142 AP-1148 Outgoings Controller
  .rubocop_todo.yml
  app/controllers/outgoings_controller.rb
  app/models/disposable_income_summary.rb
  app/models/outgoings/housing_cost.rb
  app/services/creators/base_creator.rb
  app/services/creators/capitals_creator.rb
  app/services/creators/dependants_creator.rb
  app/services/creators/outgoings_creator.rb
  app/services/creators/properties_creator.rb
  app/services/creators/state_benefits_creator.rb
  config/initializers/apipie.rb
  db/migrate/20191230112428_create_new_outgoings.rb
  db/migrate/20191230141019_remove_housing_cost_type.rb
  db/schema.rb
  doc/apipie_examples.json
  spec/requests/outgoings_spec.rb
  spec/services/creators/outgoings_creator_spec.rb
Labels: ready for code review

#143 Update applicants_controller
  app/controllers/applicants_controller.rb
Labels: Approved
