Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2020-04, with the labels that each got.

#217 Update integration test handling
  .circleci/config.yml
  README.md
  spec/fixtures/integration_test_data.xlsx
  spec/integration/test_runner_spec.rb
  spec/spec_helper.rb
Labels: ready for code review

#218 Fix the workflow
  .github/workflows/manual-integration-tests.yml
Labels: ready for code review

#221 AP1348 Update dependant threshold allowances for 6th april
  config/thresholds/6-Apr-2020.yml
  spec/services/calculators/dependant_allowance_calculator_spec.rb
Labels: Approved, ready for code review

#224 AP-1374 monthly breakdown
  app/controllers/other_incomes_controller.rb
  app/models/other_income_source.rb
  app/services/collators/gross_income_collator.rb
  app/services/creators/other_incomes_creator.rb
  app/services/decorators/gross_income_summary_decorator.rb
  app/services/decorators/monthly_income_equivalent_decorator.rb
  db/migrate/20200420132900_add_fields_to_gross_income_summary.rb
  db/schema.rb
  doc/apipie_examples.json
  spec/factories/other_income_source_factory.rb
  spec/factories/state_benefit_factory.rb
  spec/requests/assessments_spec.rb
  spec/requests/other_incomes_spec.rb
  spec/services/calculators/state_benefits_calculator_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/creators/other_incomes_creator_spec.rb
  spec/services/decorators/gross_income_summary_decorator_spec.rb
  spec/services/decorators/other_income_source_decorator_spec.rb
  spec/services/decorators/state_benefit_decorator_spec.rb
  spec/services/utilities/payment_period_analyser_spec.rb
Labels: ready for code review

#228 Fix bug preventing noisy output of integration tests
  .rubocop.yml
  lib/integration_helpers/expected_result.rb
  lib/tasks/integration.rake
  spec/integration/test_runner_spec.rb
Labels: Approved

#229 AP-1381 Categorise outgoings in response
  app/controllers/outgoings_controller.rb
  app/models/disposable_income_summary.rb
  app/models/outgoings/legal_aid.rb
  app/services/collators/legal_aid_collator.rb
  app/services/collators/outgoings_collator.rb
  app/services/creators/outgoings_creator.rb
  app/services/decorators/disposable_income_summary_decorator.rb
  app/services/decorators/gross_income_summary_decorator.rb
  app/services/decorators/monthly_outgoing_equivalent_decorator.rb
  app/services/workflows/non_passported_workflow.rb
  db/migrate/20200424071046_add_legal_aid_to_disposable_income_summary.rb
  db/schema.rb
  doc/apipie_examples.json
  spec/factories/disposable_income_summary_factory.rb
  spec/factories/outgoing_factory.rb
  spec/requests/assessments_spec.rb
  spec/requests/outgoings_spec.rb
  spec/services/collators/legal_aid_collator_spec.rb
  spec/services/collators/outgoings_collator_spec.rb
  spec/services/creators/outgoings_creator_spec.rb
  spec/services/decorators/disposable_income_summary_decorator_spec.rb
  spec/services/decorators/gross_income_summary_decorator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
Labels: ready for code review
