Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2020-06, with the labels that each got.

#258 AP-1360 Update docs and remove V1
  README.md
  app/controllers/assessments_controller.rb
  app/controllers/other_incomes_controller.rb
  app/controllers/state_benefit_type_controller.rb
  app/controllers/state_benefits_controller.rb
  app/models/assessment.rb
  app/services/decorators/result_decorator.rb
  config/initializers/apipie.rb
  doc/apipie_examples.json
  spec/requests/assessments_spec.rb
  spec/requests/state_benefit_types_spec.rb
  spec/services/decorators/result_decorator_spec.rb
Labels: ready for code review

#259 AP154 Update assessments post response
  README.md
  app/controllers/assessments_controller.rb
  app/services/creators/assessment_creator.rb
  doc/apipie_examples.json
  spec/integration/remarks_spec.rb
  spec/integration/test_runner_spec.rb
  spec/requests/assessments_spec.rb
  spec/services/creators/assessment_creator_spec.rb
Labels: Approved

#265 AP1435 Capture all errors in the application controller
  app/controllers/application_controller.rb
  app/services/creators/applicant_creator.rb
  app/services/creators/other_incomes_creator.rb
  spec/requests/application_controller_spec.rb
  spec/services/creators/applicant_creator_spec.rb
  spec/services/creators/other_incomes_creator_spec.rb
Labels: ready for code review

#271 Ap 1472 calc error
  app/services/collators/disposable_income_collator.rb
  spec/services/collators/disposable_income_collator_spec.rb
Labels: Approved, ready for code review

#270 AP1464 Add irregular income endpoint
  app/controllers/irregular_incomes_controller.rb
  app/models/gross_income_summary.rb
  app/models/irregular_income_payment.rb
  app/models/other_income_source.rb
  app/services/base_workflow_service.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/creators/irregular_income_creator.rb
  app/services/decorators/gross_income_summary_decorator.rb
  app/services/decorators/irregular_income_payments_decorator.rb
  app/services/decorators/monthly_income_equivalent_decorator.rb
  config/routes.rb
  db/migrate/20200611165619_add_monthly_student_loan_to_gross_income_summary.rb
  db/migrate/20200612123146_create_irregular_income_payments.rb
  db/schema.rb
  doc/apipie_examples.json
  spec/factories/gross_income_summary_factory.rb
  spec/factories/irregular_income_payment_factory.rb
  spec/factories/other_income_source_factory.rb
  spec/integration/remarks_spec.rb
  spec/models/irregular_income_payment_spec.rb
  spec/requests/irregular_incomes_spec.rb
  spec/services/assessors/gross_income_assessor_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/creators/irregular_income_creator_spec.rb
  spec/services/decorators/gross_income_summary_decorator_spec.rb
  spec/services/decorators/irregular_income_payments_decorator_spec.rb
  spec/services/decorators/monthly_income_equivalent_decorator_spec.rb
Labels: Changes requested, ready for code review

#272 BugFix - Test total gross income in gross income collator
  app/services/collators/gross_income_collator.rb
  spec/services/collators/gross_income_collator_spec.rb
Labels: ready for code review

#276 AP1467 Update CFE Integration tests to use irregular income/student loan
  config/initializers/apipie.rb
  doc/apipie_examples.json
  lib/integration_helpers/actual_result.rb
  lib/integration_helpers/expected_result.rb
  lib/integration_helpers/irregular_income_payload_generator.rb
  spec/integration/ap_1367_spec.rb
  spec/integration/test_runner_spec.rb
  spec/integration_helpers/irregular_income_payload_generator_spec.rb
Labels: ready for code review
