Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2020-11, with the labels that each got.

#329 AP-1747: multi benefit flagging
  app/controllers/state_benefits_controller.rb
  app/services/creators/state_benefits_creator.rb
  app/services/remark_generators/multi_benefit_checker.rb
  app/services/remark_generators/orchestrator.rb
  app/services/remarks.rb
  db/migrate/20201019103924_add_flags_to_state_benefit_payment.rb
  db/schema.rb
  doc/apipie_examples.json
  spec/factories/state_benefit_payment_factory.rb
  spec/requests/state_benefits_spec.rb
  spec/services/remark_generators/multi_benefit_checker_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
Labels: ready for code review

#337 Ap 1515 helm3
  .circleci/config.yml
  bin/delete_uat_release.sh
  bin/uat_deploy
  deploy/helm/Chart.lock
  deploy/helm/Chart.yaml
  deploy/helm/charts/postgresql-8.10.13.tgz
  deploy/helm/charts/postgresql-8.10.14.tgz
  deploy/helm/requirements.lock
  deploy/helm/requirements.yaml
Labels: Approved

#342 Tech-debt: update ruby to 2.7
  .circleci/config.yml
  .github/workflows/manual-integration-tests.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  app/controllers/assessments_controller.rb
  app/services/calculators/monthly_salary_calculator.rb
  app/services/creators/assessment_creator.rb
  app/services/creators/base_creator.rb
  spec/services/creators/assessment_creator_spec.rb
  spec/services/creators/irregular_income_creator_spec.rb
  spec/services/creators/other_incomes_creator_spec.rb
  spec/support/salary_pattern_generator.rb
Labels: Approved

#349 AP-1775: webpack for jquery
  .browserslistrc
  .gitignore
  .rubocop.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/views/layouts/apipie_override.html.erb
  app/webpack/images/favicon.ico
  app/webpack/packs/application.js
  babel.config.js
  bin/webpack
  bin/webpack-dev-server
  config/initializers/apipie.rb
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  package.json
  postcss.config.js
  public/apidocs/javascripts/bundled/jquery.js
  yarn.lock
Labels: Approved

#350 AP-1806 Fix flagging of childcare payments
  app/services/concerns/exemptable.rb
  app/services/remark_generators/amount_variation_checker.rb
  app/services/remark_generators/base_checker.rb
  app/services/remark_generators/frequency_checker.rb
  app/services/remark_generators/multi_benefit_checker.rb
  spec/integration/ap_1367_spec.rb
  spec/services/remark_generators/amount_variation_checker_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
Labels: Approved, UAT

#283 AP-1491 rewrite Frequency calculations
  Gemfile
  Gemfile.lock
  app/models/bank_holiday.rb
  app/models/concerns/monthly_equivalent_calculator.rb
  app/services/bank_holiday_retriever.rb
  app/services/calculators/monthly_salary_calculator.rb
  app/services/remark_generators/frequency_checker.rb
  app/services/utilities/calendar_monthly_period_analyser.rb
  app/services/utilities/date_slope.rb
  app/services/utilities/payment_period_analyser.rb
  app/services/utilities/regular_period_analyser.rb
  app/services/utilities/time_series_calculator.rb
  app/services/utilities/working_day_calculator.rb
  db/migrate/20200701130452_create_bank_holidays.rb
  db/schema.rb
  spec/factories/bank_holiday_factory.rb
  spec/integration/ap_1367_spec.rb
  spec/integration/remarks_spec.rb
  spec/integration/test_runner_spec.rb
  spec/models/bank_holiday_spec.rb
  spec/models/other_income_source_spec.rb
  spec/requests/assessments_spec.rb
  spec/services/bank_holiday_retriever_spec.rb
  spec/services/calculators/housing_costs_calculator_spec.rb
  spec/services/calculators/monthly_salary_calculator_spec.rb
  spec/services/calculators/state_benefits_calculator_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/collators/legal_aid_collator_spec.rb
  spec/services/collators/maintenance_collator_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/utilities/calendar_monthly_period_analyser_spec.rb
  spec/services/utilities/date_slope_spec.rb
  spec/services/utilities/payment_period_analyser_spec.rb
  spec/services/utilities/regular_period_analyser_spec.rb
  spec/services/utilities/time_series_calculator_spec.rb
Labels: Approved, ready for code review
