Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2020-07, with the labels that each got.

#280 Fix: pluralise other incomes
  app/controllers/irregular_incomes_controller.rb
  config/initializers/apipie.rb
  config/routes.rb
  doc/apipie_examples.json
  spec/integration/test_runner_spec.rb
  spec/requests/irregular_incomes_spec.rb
Labels: ready for code review

#278 remove student_loan from other_incomes
  app/models/other_income_source.rb
  app/services/collators/childcare_collator.rb
  app/services/decorators/gross_income_summary_decorator.rb
  spec/factories/gross_income_summary_factory.rb
  spec/factories/other_income_source_factory.rb
  spec/integration/ap_1367_spec.rb
  spec/integration/remarks_spec.rb
  spec/requests/other_incomes_spec.rb
  spec/services/collators/childcare_collator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/creators/other_incomes_creator_spec.rb
  spec/services/decorators/gross_income_summary_decorator_spec.rb
Labels: Approved, ready for code review

#281 AP-1441 Add client id to integration tests
  README.md
  lib/integration_helpers/deeply_nested_payload_generator.rb
  spec/integration_helpers/deeply_nested_payload_generator_spec.rb
Labels: ready for code review

#282 Ap 1487 upd8 k8s cfe
  deploy/helm/charts/postgresql-3.18.3.tgz
  deploy/helm/charts/postgresql-8.10.13.tgz
  deploy/helm/requirements.lock
  deploy/helm/requirements.yaml
  deploy/helm/templates/deployment_web.yaml
  deploy/helm/templates/ingress.yaml
Labels: Approved

#286 Bump the cache action to v2
  .github/workflows/manual-integration-tests.yml
Labels: ready for code review

#290 Add new cops
  .rubocop.yml
Labels: ready for code review

#292 Fix: Add a debug statement
  .github/workflows/manual-integration-tests.yml
Labels: ready for code review
