Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2021-01, with the labels that each got.

#389 Update readme to add pry-rescue details
  README.md
Labels: Approved

#386 BugFix Don't send exception object to Raven.capture message
  app/controllers/application_controller.rb
  spec/requests/application_controller_spec.rb
Labels: Approved, UAT

#398 AP-1921 cash transactions endpoint
  app/constants/cfe_constants.rb
  app/controllers/capitals_controller.rb
  app/controllers/cash_transactions_controller.rb
  app/controllers/explicit_remarks_controller.rb
  app/controllers/irregular_incomes_controller.rb
  app/controllers/other_incomes_controller.rb
  app/controllers/outgoings_controller.rb
  app/controllers/properties_controller.rb
  app/controllers/state_benefits_controller.rb
  app/controllers/vehicles_controller.rb
  app/models/applicant.rb
  app/models/bank_holiday.rb
  app/models/cash_transaction.rb
  app/models/cash_transaction_category.rb
  app/models/dated_struct.rb
  app/models/dependant.rb
  app/models/explicit_remark.rb
  app/models/gross_income_summary.rb
  app/models/irregular_income_payment.rb
  app/models/other_income_source.rb
  app/models/vehicle.rb
  app/services/calculators/monthly_income_converter.rb
  app/services/creators/cash_transactions_creator.rb
  app/services/creators/outgoings_creator.rb
  app/services/govuk_bank_holiday_retriever.rb
  app/services/remarks.rb
  app/validators/currency_validator.rb
  app/validators/date_validator.rb
  config/initializers/apipie.rb
  config/routes.rb
  db/migrate/20210114115638_create_cash_transaction_categories.rb
  db/migrate/20210114115829_create_cash_transactions.rb
  db/schema.rb
  doc/apipie_examples.json
  spec/factories/assessment_factory.rb
  spec/factories/disposable_income_summary_factory.rb
  spec/factories/other_income_payment_factory.rb
  spec/factories/other_income_source_factory.rb
  spec/factories/state_benefit_factory.rb
  spec/factories/state_benefit_payment_factory.rb
  spec/integration/remarks_spec.rb
  spec/models/assessment_spec.rb
  spec/models/bank_holiday_spec.rb
  spec/models/cash_transaction_category_spec.rb
  spec/requests/cash_transactions_spec.rb
  spec/requests/irregular_incomes_spec.rb
  spec/services/bank_holiday_retriever_spec.rb
  spec/services/calculators/housing_costs_calculator_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/collators/housing_costs_collator_spec.rb
  spec/services/creators/cash_transactions_creator_spec.rb
  spec/services/creators/outgoings_creator_spec.rb
  spec/services/decorators/other_income_source_decorator_spec.rb
  spec/services/decorators/state_benefit_decorator_spec.rb
  spec/services/remark_generators/amount_variation_checker_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/remark_generators/multi_benefit_checker_spec.rb
  spec/services/utilities/payment_period_data_extractor_spec.rb
  spec/validators/currency_validator_spec.rb
  spec/validators/date_validator_spec.rb
Labels: ready for code review

#406 FIX and update policy disregards
  app/services/calculators/pensioner_capital_disregard_calculator.rb
  spec/requests/assessments_spec.rb
  spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
Labels: ready for code review

#405 AP-1979: Add new fields to gross income summary with ability to call assessment version 3
  app/constants/cfe_constants.rb
  app/controllers/api/statuses_controller.rb
  app/controllers/assessments_controller.rb
  app/models/assessment.rb
  app/models/cash_transaction.rb
  app/models/cash_transaction_category.rb
  app/models/gross_income_summary.rb
  app/models/other_income_source.rb
  app/services/collators/gross_income_collator.rb
  app/services/creators/cash_transactions_creator.rb
  app/services/decorators/assessment_decorator.rb
  app/services/decorators/gross_income_summary_decorator.rb
  app/services/decorators/monthly_income_equivalent_decorator.rb
  app/services/decorators/other_income_source_decorator.rb
  db/migrate/20210122165708_add_bank_cash_transactions_to_gross_income_summary.rb
  db/schema.rb
  spec/factories/assessment_factory.rb
  spec/factories/cash_transaction_category_factory.rb
  spec/factories/cash_transaction_factory.rb
  spec/factories/gross_income_summary_factory.rb
  spec/factories/other_income_source_factory.rb
  spec/models/assessment_spec.rb
  spec/requests/assessments_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
  spec/services/decorators/gross_income_summary_decorator_spec.rb
  spec/services/decorators/other_income_source_decorator_spec.rb
Labels: Approved, UAT
