Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2022-05, with the labels that each got.

#900 AP-3067 Investigate slow CFE responses
  app/controllers/application_controller.rb
  app/models/request_log.rb
  db/migrate/20220429103502_create_requests_table.rb
  db/schema.rb
Labels: ready for code review

#926 AP-2808 add delete script and step to circle config
  .circleci/config.yml
  bin/delete_dependabot_deployment
  bin/uat_deploy
Labels: Approved

#929 AP-3150 Make V4 the default version
  app/constants/cfe_constants.rb
  spec/integration/ap_1367_spec.rb
  spec/integration/ap_2996_employment_remarks_spec.rb
  spec/integration/policy_disregards_spec.rb
  spec/integration/remarks_spec.rb
  spec/requests/assessments_controller_spec.rb
Labels: Changes requested

#930 Fix for blunt average calculation
  app/constants/cfe_constants.rb
  app/services/remark_generators/frequency_checker.rb
  app/services/remark_generators/orchestrator.rb
  app/services/utilities/employment_income_monthly_equivalent_calculator.rb
  lib/integration_helpers/test_case/employment_collection.rb
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/four-weekly_payment/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/four-weekly_payment/varying_amounts/populates_the_gross_income_monthly_equiv_with_calculated_amount.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/monthly_payment/amounts_varying_60/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/monthly_payment/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/two-weekly_payments/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/blunt_average/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/blunt_average/varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/four-weekly_payment/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/four-weekly_payment/varying_amounts/populates_the_gross_income_monthly_equiv_with_calculated_amount.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/monthly_payment/amounts_varying_60/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/monthly_payment/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/two-weekly_payments/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/weekly_payments/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/weekly_payments/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/factories/employment_factory.rb
  spec/fixtures/bank-holidays.json
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/remark_generators/orchestrator_spec.rb
  spec/services/utilities/employment_income_monthly_equivalent_calculator_spec.rb
Labels: Approved

#927 Ap 3113 remove apipie json schema
  app/controllers/applicants_controller.rb
  app/services/creators/applicant_creator.rb
  app/validators/json_validator.rb
  config/initializers/apipie.rb
  public/schemas/applicant.json.erb
  public/schemas/common.json
  spec/requests/applicants_controller_spec.rb
  spec/requests/swagger_docs/v4/applicants_spec.rb
  spec/services/creators/applicant_creator_spec.rb
  spec/validators/json_validator_spec.rb
Labels: Approved
