Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2022-08, with the labels that each got.

#1029 ap-3163: covert state_benefits_controller to use json_schema
  app/controllers/state_benefits_controller.rb
  app/models/state_benefit_payment.rb
  app/services/creators/state_benefits_creator.rb
  config/initializers/apipie.rb
  public/schemas/state_benefits.json.erb
  spec/requests/state_benefits_controller_spec.rb
  spec/requests/swagger_docs/v4/state_benefits_spec.rb
  spec/requests/swagger_docs/v5/state_benefits_spec.rb
  spec/services/creators/state_benefits_creator_spec.rb
Labels: Approved

#1032 AP-3360 Enable HHH CIT V5 Integration tests
  app/models/gross_income_summary.rb
  app/services/decorators/v5/matter_type_result_decorator.rb
  app/services/decorators/v5/result_summary_decorator.rb
  app/services/legal_framework_api/mock_threshold_waivers.rb
  app/services/utilities/proceeding_type_threshold_populator.rb
  app/services/workflows/non_passported_workflow.rb
  lib/integration_helpers/test_case/applicant.rb
  lib/integration_helpers/test_case/worksheet.rb
  spec/cassettes/IntegrationTests_TestRunner/run_integration_tests/processes_all_the_tests_on_all_the_sheets.yml
  spec/services/legal_framework_api/mock_threshold_waivers_spec.rb
  spec/services/utilities/proceeding_type_threshold_populator_spec.rb
Labels: ready for code review

#1023 AP-3158 add JSON schema validation to irregular incomes
  app/controllers/irregular_incomes_controller.rb
  app/services/creators/irregular_income_creator.rb
  public/schemas/irregular_incomes.json.erb
  spec/requests/irregular_incomes_controller_spec.rb
  spec/requests/swagger_docs/v4/irregular_incomes_spec.rb
  spec/requests/swagger_docs/v5/irregular_incomes_spec.rb
  spec/services/creators/irregular_income_creator_spec.rb
Labels: Approved

#1033 AP-3360 correction - remove specs for matter type on V5 responses
  lib/integration_helpers/test_case/v5/result_comparer.rb
Labels: Approved

#1044 Fix: Pre APIPIE removal tidy
  config/initializers/apipie.rb
  spec/requests/capitals_controller_spec.rb
  spec/requests/properties_controller_spec.rb
Labels: ready for code review

#1043 AP-3364: Update the ingress classname handling
  deploy/helm/templates/ingress.yaml
  deploy/helm/values-production.yaml
  deploy/helm/values-staging.yaml
  deploy/helm/values-uat.yaml
Labels: Approved, On Hold

#1045 AP-3162: Remove APIPIE from state_benefit_types
  app/controllers/state_benefit_type_controller.rb
  config/initializers/apipie.rb
  spec/requests/state_benefit_type_controller_spec.rb
Labels: Approved, UAT

#1065 Update README to include required envvar
  README.md
Labels: Approved
