Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2022-11, with the labels that each got.

#1169 Fix flaky integration spec
  spec/integration/v5_full_assessment_spec.rb
Labels: Approved

#1168 Fix employment without payments bug
  app/models/employment.rb
  spec/models/employment_spec.rb
Labels: Approved

#1165 EL-428: Acknowledge and account for SMOD assets
  app/models/capital_item.rb
  app/models/capital_summary.rb
  app/models/property.rb
  app/models/vehicle.rb
  app/services/calculators/subject_matter_of_dispute_disregard_calculator.rb
  app/services/collators/capital_collator.rb
  app/services/creators/capitals_creator.rb
  app/services/decorators/v5/capital_result_decorator.rb
  app/services/decorators/v5/capital_summary_decorator.rb
  config/thresholds/2021-04-12.yml
  config/thresholds/2022-04-11.yml
  db/migrate/20221027150350_add_smod_to_capital_items.rb
  db/schema.rb
  public/schemas/capital.json.erb
  public/schemas/properties.json.erb
  public/schemas/vehicles.json.erb
  spec/factories/capital_item_factory.rb
  spec/factories/property_factory.rb
  spec/factories/vehicle_factory.rb
  spec/integration/v5_full_assessment_spec.rb
  spec/requests/swagger_docs/v5/capitals_spec.rb
  spec/requests/swagger_docs/v5/properties_spec.rb
  spec/requests/swagger_docs/v5/vehicles_spec.rb
  spec/services/calculators/subject_matter_of_dispute_disregard_calculator_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/creators/capitals_creator_spec.rb
  spec/services/creators/properties_creator_spec.rb
  spec/services/decorators/v5/capital_result_decorator_spec.rb
  spec/services/decorators/v5/capital_summary_decorator_spec.rb
  swagger/v5/swagger.yaml
Labels: Approved

#1187 AP-3604: Remove web-packer and dependencies
  .browserslistrc
  .circleci/config.yml
  .github/dependabot.yml
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  app/webpack/images/favicon.ico
  app/webpack/packs/application.js
  babel.config.js
  bin/webpack
  bin/webpack-dev-server
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  package.json
  postcss.config.js
Labels: ready for code review

#1199 Fix for child care eligibility rules with regular transaction
  app/services/collators/childcare_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/concerns/childcare_eligibility.rb
  lib/integration_helpers/test_case/applicant.rb
  spec/factories/dependant_factory.rb
  spec/services/collators/regular_outgoings_collator_spec.rb
Labels: approved, UAT

#1200 AP-3657: Update Section 8 proceeding type values
  app/constants/cfe_constants.rb
  app/models/proceeding_type.rb
  app/models/proceeding_type_threshold.rb
  public/schemas/proceeding_types.json.erb
  spec/factories/proceeding_type_factory.rb
  spec/models/proceeding_type_spec.rb
  spec/models/proceeding_type_threshold_spec.rb
  spec/services/collators/gross_income_collator_spec.rb
Labels: ready for review
