Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2022-03, with the labels that each got.

#824 Fix GOV.UK Rubocop Rails/Output offences
  .rubocop_todo.yml
  db/migration_helpers/category_seeder.rb
  db/seeds.rb
Labels: Approved

#823 Fix GOV.UK Rubocop Style/TrailingCommaInArrayLiteral offences
  .rubocop_todo.yml
  app/services/creators/cash_transactions_creator.rb
  lib/integration_helpers/test_case/irregular_income.rb
  lib/integration_helpers/test_case/vehicle.rb
  lib/v4_migrators/integration_test_migrator.rb
  spec/fixtures/assessment_request_fixture.rb
  spec/fixtures/assessment_response_fixture.rb
  spec/integration/policy_disregards_spec.rb
  spec/integration/remarks_spec.rb
  spec/integration_helpers/test_case/employment_collection_spec.rb
  spec/lib/integration_helpers/test_case/v4/result_comparer_spec.rb
  spec/models/explicit_remark_spec.rb
  spec/requests/assessments_controller_spec.rb
  spec/requests/capitals_controller_spec.rb
  spec/requests/cash_transactions_controller_spec.rb
  spec/requests/employments_controller_spec.rb
  spec/requests/explicit_remarks_controller_spec.rb
  spec/requests/irregular_incomes_controller_spec.rb
  spec/requests/other_incomes_controller_spec.rb
  spec/requests/outgoings_controller_spec.rb
  spec/requests/properties_controller_spec.rb
  spec/requests/state_benefits_controller_spec.rb
  spec/services/assessors/assessment_proceeding_type_assessor_spec.rb
  spec/services/creators/capitals_creator_spec.rb
  spec/services/creators/cash_transactions_creator_spec.rb
  spec/services/creators/employments_creator_spec.rb
  spec/services/creators/explicit_remarks_creator_spec.rb
  spec/services/creators/irregular_income_creator_spec.rb
  spec/services/creators/other_incomes_creator_spec.rb
  spec/services/creators/outgoings_creator_spec.rb
  spec/services/creators/properties_creator_spec.rb
  spec/services/decorators/v4/capital_result_decorator_spec.rb
  spec/services/decorators/v4/disposable_income_result_decorator_spec.rb
  spec/services/decorators/v4/gross_income_decorator_spec.rb
  spec/services/decorators/v4/gross_income_result_decorator_spec.rb
  spec/services/decorators/v4/matter_type_result_decorator_spec.rb
  spec/services/decorators/v4/proceeding_types_result_decorator_spec.rb
  spec/services/govuk_bank_holiday_retriever_spec.rb
  spec/services/legal_framework_api/query_service_spec.rb
  spec/services/remark_generators/amount_variation_checker_spec.rb
  spec/services/remark_generators/frequency_checker_spec.rb
  spec/services/utilities/payment_period_data_extractor_spec.rb
  spec/support/faker/other_income_source.rb
Labels: Approved

#822 Fix GOV.UK Rubocop RSpec/VerifiedDoubles offences
  .rubocop_todo.yml
  spec/models/bank_holiday_spec.rb
  spec/models/other_income_source_spec.rb
  spec/services/collators/capital_collator_spec.rb
  spec/services/collators/dependants_allowance_collator_spec.rb
  spec/services/decorators/v3/assessment_decorator_spec.rb
  spec/services/decorators/v3/capital_summary_decorator_spec.rb
  spec/services/decorators/v3/gross_income_summary_decorator_spec.rb
  spec/services/decorators/v4/assessment_decorator_spec.rb
  spec/services/legal_framework_api/response_error_spec.rb
  spec/services/workflows/self_employed_workflow_spec.rb
Labels: Approved

#825 Ap 2914 emp integration tests
  config/environments/test.rb
  config/thresholds/2018-04-08.yml
  config/thresholds/2019-04-08.yml
  config/thresholds/2020-04-06.yml
  config/thresholds/2021-01-28.yml
  config/thresholds/test-jan.yml
  db/schema.rb
  lib/integration_helpers/test_case/employment_collection.rb
  lib/integration_helpers/test_case/v4/expected_result.rb
  lib/integration_helpers/test_case/v4/remarks_comparer.rb
  lib/integration_helpers/test_case/v4/result_comparer.rb
  spec/integration_helpers/test_case/employment_collection_spec.rb
  spec/lib/integration_helpers/test_case/v4/remarks_comparer_spec.rb
  spec/lib/integration_helpers/test_case/v4/result_comparer_spec.rb
Labels: ready for code review

#821 Tech-debt: Update Ruby to 3.1.1
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Approved, UAT

#826 AP-2883 employment integration tests
  app/services/calculators/multiple_employments_calculator.rb
  app/services/calculators/tax_ni_refund_calculator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/utilities/employment_income_monthly_equivalent_calculator.rb
  app/services/utilities/regular_period_analyser.rb
  lib/integration_helpers/test_case/v4/expected_result.rb
  lib/integration_helpers/test_case/v4/remarks_comparer.rb
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/blunt_average/non_varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/cassettes/Utilities_EmploymentIncomeMonthlyEquivalentCalculator/valid_payment_period/blunt_average/varying_amounts/populates_monthly_equivalent_field_with_gross_income.yml
  spec/integration/ap_1367_spec.rb
  spec/integration/test_runner_spec.rb
  spec/services/calculators/tax_ni_refund_calculator_spec.rb
  spec/services/utilities/employment_income_monthly_equivalent_calculator_spec.rb
Labels: Approved

#838 AP-2937 Add CODEOWNERS file
  docs/CODEOWNERS
Labels: Approved

#837 Fix remaining GOVUK rubocop issues
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile.lock
  app/services/creators/applicant_creator.rb
  app/services/creators/capitals_creator.rb
  app/services/creators/cash_transactions_creator.rb
  app/services/creators/dependants_creator.rb
  app/services/creators/employments_creator.rb
  app/services/creators/explicit_remarks_creator.rb
  app/services/creators/irregular_income_creator.rb
  app/services/creators/other_incomes_creator.rb
  app/services/creators/properties_creator.rb
  app/services/creators/state_benefits_creator.rb
  app/services/creators/vehicle_creator.rb
  spec/models/assessment_spec.rb
  spec/models/eligibility/gross_income_spec.rb
Labels: Approved

#844 AP-2903 make client_id mandatory
  app/controllers/employments_controller.rb
  db/migrate/20220317185108_make_client_id_mandatory.rb
  db/schema.rb
  spec/requests/employments_controller_spec.rb
  spec/services/creators/employments_creator_spec.rb
Labels: ready for code review

#860 Ap 2982 show actual disposable income
  app/services/collators/disposable_income_collator.rb
  config/thresholds/2018-04-08.yml
  config/thresholds/2019-04-08.yml
  config/thresholds/2020-04-06.yml
  config/thresholds/2021-01-28.yml
  config/thresholds/2021-04-12.yml
  config/thresholds/test-jan.yml
  spec/services/calculators/income_contribution_calculator_spec.rb
  spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
  spec/services/collators/disposable_income_collator_spec.rb
Labels: ready for code review

#863 Update apipie-rails gem to version 0.6.0
  Gemfile
  Gemfile.lock
Labels: ready for code review
