Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2022-09, with the labels that each got.

#1073 Fix: Deploying via Circle CI
  Dockerfile
Labels: ready for code review

#1072 AP-3108 Ensure code coverage at 100%
  config/environments/test.rb
  spec/factories/employment_factory.rb
Labels: ready for code review

#1076 [AP-3439] add regular transactions
  .overcommit.yml
  app/controllers/regular_transactions_controller.rb
  app/models/gross_income_summary.rb
  app/models/regular_transaction.rb
  app/services/calculators/housing_costs_calculator.rb
  app/services/collators/childcare_collator.rb
  app/services/collators/disposable_income_collator.rb
  app/services/collators/gross_income_collator.rb
  app/services/collators/regular_income_collator.rb
  app/services/collators/regular_outgoings_collator.rb
  app/services/concerns/monthly_equivalent_calculatable.rb
  app/services/concerns/transactions.rb
  app/services/creators/regular_transactions_creator.rb
  app/services/utilities/employment_income_monthly_equivalent_calculator.rb
  app/services/workflows/non_passported_workflow.rb
  config/routes.rb
  db/migrate/20220901175043_create_regular_transactions.rb
  db/schema.rb
  lib/integration_helpers/test_case/regular_transaction.rb
  lib/integration_helpers/test_case/regular_transactions_collection.rb
  lib/integration_helpers/test_case/v5/result_comparer.rb
  lib/integration_helpers/test_case/worksheet.rb
  public/schemas/regular_transactions.json.erb
  spec/factories/regular_transactions.rb
  spec/integration/test_runner_spec.rb
  spec/lib/integration_helpers/test_case/regular_transaction_spec.rb
  spec/lib/integration_helpers/test_case/regular_transactions_collection_spec.rb
  spec/models/gross_income_summary_spec.rb
  spec/models/regular_transaction_spec.rb
  spec/requests/regular_transactions_controller_spec.rb
  spec/requests/swagger_docs/v5/regular_transactions_spec.rb
  spec/services/collators/regular_income_collator_spec.rb
  spec/services/collators/regular_outgoings_collator_spec.rb
  spec/services/creators/regular_transactions_creator_spec.rb
  spec/services/workflows/non_passported_workflow_spec.rb
  spec/spec_helper.rb
  swagger/v5/swagger.yaml
Labels: Approved, UAT

#1086 Ap 3164 convert vehicles controller json schema
  app/controllers/vehicles_controller.rb
  app/models/vehicle.rb
  app/services/creators/vehicle_creator.rb
  app/validators/cfe_date_validator.rb
  public/schemas/vehicles.json.erb
  spec/requests/outgoings_controller_spec.rb
  spec/requests/swagger_docs/v4/vehicles_spec.rb
  spec/requests/swagger_docs/v5/vehicles_spec.rb
  spec/requests/vehicles_controller_spec.rb
  spec/services/creators/state_benefits_creator_spec.rb
  spec/services/creators/vehicle_creation_service_spec.rb
  spec/validators/cfe_date_validator_spec.rb
Labels: Approved

#1099 Fix: Allow the test action to be triggered via Github
  .github/workflows/manual-integration-tests.yml
Labels: ready for code review

#1090 Run individual workersheets as separate examples using rspec
  .github/workflows/manual-integration-tests.yml
  bin/ispec
  spec/integration/test_runner_spec.rb
Labels: Approved

#1109 AP-3496 Return error payload instead of raising an exception
  app/controllers/assessments_controller.rb
  app/services/workflows/main_workflow.rb
  spec/requests/assessments_controller_spec.rb
  spec/services/workflows/main_workflow_spec.rb
Labels: Approved

#1112 Do not force refresh on integration test worksheets on rspec run
  spec/integration/test_runner_spec.rb
Labels: Approved

#1115 [Security] Selectively bump terser to 5.15.0
  package.json
  yarn.lock
Labels: ready for code review

#1111 AP-3313 Cronjob to delete stale assessments
  app/constants/cfe_constants.rb
  app/models/assessment.rb
  app/services/creators/capital_eligibility_creator.rb
  app/services/cull_stale_assessments_service.rb
  deploy/helm/templates/cronjob-cull-stale-assessments.yaml
  lib/tasks/cull_stale_assessments.rake
  spec/factories/assessment_error_factory.rb
  spec/factories/assessment_factory.rb
  spec/factories/cash_transaction_category_factory.rb
  spec/factories/regular_transaction_factory.rb
  spec/factories/request_log_factory.rb
  spec/services/cull_stale_assessments_service_spec.rb
Labels: Approved
