Repository ministryofjustice/check-financial-eligibility, pull requests merged in 2023-01, with the labels that each got.

#1247 Fix: Update the github action versions
  .github/workflows/brakeman-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-image-scan.yaml
  .github/workflows/manual-integration-tests.yml
Labels: approved

#1291 Use reusable Brakeman GitHub Action
  .github/workflows/brakeman-analysis.yml
Labels: approved

#1260 Update Ruby to v3.2.0
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: UAT

#1297 Use reusable snyk workflow to scan docker images
  .github/workflows/docker-image-scan.yaml
Labels: ready for review
